### ISSUE TITLE
Use loom checker?

### ISSUE THREAD

**Issue by Restioson** [not-a-seagull/spinny#1]
Hi, thanks for writing this crate :) At first glance, it seems that the tests are a little basic, so maybe it would be good to use [loom](https://github.com/tokio-rs/loom) to check the correctness of the RwLock's inner atomic operations? I don't know how this interacts with lock_api at all.

**Comment by Restioson** [comment]
This may be useful? https://github.com/tokio-rs/loom/issues/162

**Comment by notgull** [comment]
Thank you for your issue. I didn't know about `loom` prior to this. I'm going to rewrite this crate using a `loom` feature. Give me some time.

It shouldn't interact with `lock_api` at all. `lock_api` only acts as a wrapper around the lock that also contains the associated data.

**Comment by Restioson** [comment]
In that case, there needs to just be a kind of facade to abstract over std and loom types. I implemented this for concurrent-queue in https://github.com/stjepang/concurrent-queue/pull/5/. For spinny, it seems like the required modification would simply be to replace [this](https://github.com/not-a-seagull/spinny/blob/ce0f10d061a52fb4d62ab3aac256c396fbf2aaa0/src/lib.rs#L8)

```rust
use core::sync::atomic::{spin_loop_hint, AtomicUsize, Ordering};
```

with this
```rust
#[cfg(not(feature = "loom"))]
use core::sync::atomic::{spin_loop_hint, AtomicUsize, Ordering};
#[cfg(feature = "loom")]
use loom::sync::atomic::{spin_loop_hint, AtomicUsize, Ordering};
```

**Comment by notgull** [comment]
This does actually have an issue, actually. This code presently relies on the fact that `AtomicUsize` can be initialized in constant contexts. This line:

```rust
const INIT: RawRwSpinlock = RawRwSpinlock(AtomicUsize::new(0));
```

causes a compilation error, as `loom`'s `AtomicUsize` cannot be initialized here. The alternative to this is to have the RawRwSpinlock be this:

```rust
pub struct RawRwSpinlock(Option<AtomicUsize>);
````

and then initialize the spinlock in the lock functions. However, the lock functions use immutable access, which means that in order to change the value of the `Option` at runtime, we need to wrap it in a primitive that allows for interior mutability:

```rust
pub struct RawRwSpinlock(UnsafeCell<Option<AtomicUsize>>);
```

However, this can cause a data race if two users try to initialize the spinlock at once. I'm not sure if there's an easy solution to this.

**Comment by Restioson** [comment]
Hmm... that seems to be a problem. I did find https://github.com/tokio-rs/loom/pull/161 so maybe this could be helpful?

**Comment by notgull** [comment]
Using a OnceCell seems like an alright solution, except for the fact that I'm essentially just putting a mutex inside of my mutex. Let me try this.

**Comment by Restioson** [comment]
Hmmm... When does this need to be locked?

Also, this could be cfg'd out only to happen with loom on. If this only need to be locked upon initialization then maybe it would still be useful for correctness checking?
